[features]
seeds = false
[programs.localnet]
solana_coding_camp = "FJ1ddJSwnigDNeyMqC1YD9RZzkykkq7ifXCm7pTnUVX4"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/vutuan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
